/**
 * Typed theme demo — uses the type-safe useTheme() generated by makeThemeType.
 *
 * Generated via:
 *   npx ink-cartridge makeThemeType ./projectTest/theme ./projectTest/theme/typed
 *
 * Run:
 *   npx tsx projectTest/theme/Theme_typed_demo.tsx
 */
import React, { useState } from 'react';
import { render, Box, Text, useInput } from 'ink';
import { ThemeProvider } from '../../src/index.js';
import { useTheme } from './typed/theme.js';

function ThemeTypedDemo() {
  const { color, style, themeId, themes, setTheme } = useTheme();
  const [idx, setIdx] = useState(themes.indexOf(themeId));

  useInput((input, key) => {
    if (key.escape || input === 'q') process.exit(0);
    if (input === 't') {
      const next = (idx + 1) % themes.length;
      setIdx(next);
      setTheme(themes[next]);
    }
  });

  return (
    <Box flexDirection="column" padding={1}>
      <Box
        borderStyle="round"
        borderColor={color('border') ?? 'gray'}
        paddingX={2}
      >
        <Text bold={style('titleBold') ?? false} color={color('primary') ?? 'white'}>
          Typed Theme Demo
        </Text>
      </Box>

      {/* Theme switcher */}
      <Box marginTop={1}>
        <Text dimColor={style('textDim') ?? false} color={color('muted')}>
          Theme: <Text bold>{themeId}</Text>  [{themes.join(', ')}]
        </Text>
      </Box>

      {/* Color swatches — all keys have autocompletion and compile-time checking */}
      <Box marginTop={1} flexDirection="column">
        <Text bold color={color('primary') ?? 'white'}>
          Colors
        </Text>
        <Text color={color('primary') ?? 'white'}>
          {'  primary  '}
          <Text backgroundColor={color('primary')} color="black">  {color('primary')}  </Text>
        </Text>
        <Text>
          {'  bg       '}
          <Text backgroundColor={color('bg')} color={color('primary')}>  {color('bg')}  </Text>
        </Text>
        <Text color={color('muted')}>
          {'  muted    '}{color('muted')}
        </Text>
        <Text color={color('danger')}>
          {'  danger   '}{color('danger')}
        </Text>
        <Text color={color('success')}>
          {'  success  '}{color('success')}
        </Text>
        <Text color={color('border')}>
          {'  border   '}{color('border')}
        </Text>
      </Box>

      {/* Style keys — all boolean */}
      <Box marginTop={1} flexDirection="column">
        <Text bold color={color('primary') ?? 'white'}>
          Styles
        </Text>
        <Text bold={style('titleBold') ?? false}>
          {'  titleBold  '}{String(style('titleBold'))}
        </Text>
        <Text dimColor={style('textDim') ?? false}>
          {'  textDim    '}{String(style('textDim'))}
        </Text>
        <Text bold={style('borderBold') ?? false}>
          {'  borderBold '}{String(style('borderBold'))}
        </Text>
      </Box>

      <Box marginTop={2}>
        <Text dimColor={style('textDim') ?? false} color={color('muted')}>
          [T] Switch theme  [Q] Quit
        </Text>
      </Box>
    </Box>
  );
}

render(
  <ThemeProvider path="./projectTest/theme" defaultTheme="dark">
    <ThemeTypedDemo />
  </ThemeProvider>,
);
