// Auto-generated by ink-cartridge makeLanguageType.
// Do not edit manually.

import { useI18n as rawUseI18n } from '../../../src/index.js';
import type { TranslationKey, TranslationParams } from './i18n-types.js';

// Module-level ref set by <LanguageProvider> via the hook.
// The typed t() function delegates to it so that callers can
// use a standalone t() without threading context manually.
let _t: ReturnType<typeof rawUseI18n>['t'] | null = null;

/**
 * Typed translation function. Drop-in replacement for the original `t`.
 *
 * Must be called inside a component tree wrapped by `<LanguageProvider>`.
 * Uses a module-level ref that is automatically set when any component
 * in the tree calls `useI18n()`.
 *
 * @param key - A translation key shared by all language files.
 * @param options - Optional params and/or context.
 */
export function t<K extends TranslationKey>(
  key: K,
  options?: { params?: TranslationParams[K]; context?: string },
): string {
  if (!_t) {
    throw new Error(
      '[ink-cartridge] typed t() called before <LanguageProvider> is mounted. Ensure a component has called useI18n() first.',
    );
  }
  return _t(key, options as any);
}

/**
 * Typed `useI18n` hook. Returns the same API as the original hook but
 * with a type-safe `t` function and updates the module-level ref so
 * that the standalone `t()` also works.
 */
export function useI18n(): Omit<ReturnType<typeof rawUseI18n>, 't'> & { t: typeof t } {
  const ctx = rawUseI18n();
  _t = ctx.t;
  return { ...ctx, t: (key: any, options?: any) => ctx.t(key, options) };
}
