import * as fs from 'node:fs';
import * as path from 'node:path';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface ThemeFile {
  /** Theme id from the file name (e.g. "dark"). */
  id: string;
  /** Flat key → value map (excluding 'id'). */
  values: Record<string, string | boolean>;
}

export interface MakeThemeTypeOptions {
  /** Directory containing {id}.json theme files. */
  sourceDir: string;
  /** Directory where the generated files will be written. */
  outputDir: string;
  /** Whether to re-generate on file changes. */
  watch: boolean;
  /** Debounce delay in milliseconds (default 500). */
  debounceMs: number;
  /** npm package name to import the original useTheme from. */
  packageName: string;
}

/* ------------------------------------------------------------------ */
/*  File scanning                                                     */
/* ------------------------------------------------------------------ */

function scanThemeFiles(dirPath: string): ThemeFile[] {
  const files: ThemeFile[] = [];

  let entries: string[];
  try {
    entries = fs.readdirSync(dirPath);
  } catch {
    return files;
  }

  for (const entry of entries.sort()) {
    if (!entry.endsWith('.json')) continue;
    const id = entry.slice(0, -'.json'.length);
    const fullPath = path.resolve(dirPath, entry);
    try {
      const raw = fs.readFileSync(fullPath, 'utf-8');
      const parsed = JSON.parse(raw) as Record<string, unknown>;
      const values: Record<string, string | boolean> = {};
      for (const [k, v] of Object.entries(parsed)) {
        if (k === 'id') continue;
        if (typeof v === 'string' || typeof v === 'boolean') {
          values[k] = v;
        }
      }
      files.push({ id, values });
    } catch {
      process.stderr.write(`[ink-cartridge] Warning: failed to parse "${entry}" — skipped\n`);
    }
  }

  return files;
}

/* ------------------------------------------------------------------ */
/*  Key analysis                                                      */
/* ------------------------------------------------------------------ */

/** Keys present in EVERY theme file. */
export function findCommonKeys(files: ThemeFile[]): string[] {
  if (files.length === 0) return [];
  const keySets = files.map((f) => new Set(Object.keys(f.values)));
  const common = new Set(keySets[0]);
  for (let i = 1; i < keySets.length; i++) {
    for (const key of common) {
      if (!keySets[i].has(key)) common.delete(key);
    }
  }
  return [...common].sort();
}

/** Classify keys into color keys (string values) and style keys (boolean values). */
export function classifyKeys(
  files: ThemeFile[],
  commonKeys: string[],
): { colorKeys: string[]; styleKeys: string[] } {
  const colorKeys: string[] = [];
  const styleKeys: string[] = [];

  for (const key of commonKeys) {
    // Peek at the first file's value type
    const val = files[0]?.values[key];
    if (typeof val === 'boolean') {
      styleKeys.push(key);
    } else {
      // string or anything else → color
      colorKeys.push(key);
    }
  }

  return { colorKeys, styleKeys };
}

/* ------------------------------------------------------------------ */
/*  Code generation                                                   */
/* ------------------------------------------------------------------ */

/** @internal Exported for testing only. */
export function generateTypesContent(
  colorKeys: string[],
  styleKeys: string[],
): string {
  const lines: string[] = [
    '// Auto-generated by ink-cartridge makeThemeType.',
    '// Do not edit manually.',
    '',
  ];

  // ThemeColorKey
  if (colorKeys.length === 0) {
    lines.push('export type ThemeColorKey = never;');
  } else {
    lines.push('export type ThemeColorKey =');
    for (let i = 0; i < colorKeys.length; i++) {
      const delim = i < colorKeys.length - 1 ? '' : ';';
      lines.push(`  | '${escapeSingleQuote(colorKeys[i])}'${delim}`);
    }
  }

  lines.push('');

  // ThemeStyleKey
  if (styleKeys.length === 0) {
    lines.push('export type ThemeStyleKey = never;');
  } else {
    lines.push('export type ThemeStyleKey =');
    for (let i = 0; i < styleKeys.length; i++) {
      const delim = i < styleKeys.length - 1 ? '' : ';';
      lines.push(`  | '${escapeSingleQuote(styleKeys[i])}'${delim}`);
    }
  }

  lines.push('');

  // Combined type
  lines.push('/** Union of all theme keys (color + style). */');
  lines.push('export type ThemeKey = ThemeColorKey | ThemeStyleKey;');
  lines.push('');

  return lines.join('\n');
}

/** @internal Exported for testing only. */
export function generateRuntimeContent(packageName: string): string {
  return (
    `// Auto-generated by ink-cartridge makeThemeType.\n` +
    `// Do not edit manually.\n` +
    `\n` +
    `import { useTheme as rawUseTheme } from '${escapeSingleQuote(packageName)}';\n` +
    `import type { ThemeColorKey, ThemeStyleKey } from './theme-types.js';\n` +
    `\n` +
    `/**\n` +
    ` * Typed theme hook. Drop-in replacement for the original \`useTheme\`.\n` +
    ` *\n` +
    ` * - \`color()\` only accepts keys classified as color values\n` +
    ` * - \`style()\` only accepts keys classified as style (boolean) values\n` +
    ` */\n` +
    `export function useTheme(): Omit<ReturnType<typeof rawUseTheme>, 'color' | 'style'> & {\n` +
    `  color: (key: ThemeColorKey) => string | undefined;\n` +
    `  style: (key: ThemeStyleKey) => boolean | undefined;\n` +
    `} {\n` +
    `  const ctx = rawUseTheme();\n` +
    `  return {\n` +
    `    ...ctx,\n` +
    `    color: (key: any) => ctx.color(key),\n` +
    `    style: (key: any) => ctx.style(key),\n` +
    `  };\n` +
    `}\n`
  );
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

/** @internal Exported for testing only. */
export function escapeSingleQuote(s: string): string {
  return s.replace(/'/g, "\\'");
}

function writeOutput(outputDir: string, typesContent: string, runtimeContent: string): void {
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(path.join(outputDir, 'theme-types.d.ts'), typesContent, 'utf-8');
  fs.writeFileSync(path.join(outputDir, 'theme.ts'), runtimeContent, 'utf-8');
}

/* ------------------------------------------------------------------ */
/*  Public API                                                         */
/* ------------------------------------------------------------------ */

/**
 * Generate type-safe theme bindings from a directory of {id}.json theme files.
 *
 * Produces two files in {@link MakeThemeTypeOptions.outputDir}:
 * - `theme-types.d.ts` — type declarations (ThemeColorKey, ThemeStyleKey, ThemeKey)
 * - `theme.ts` — typed `useTheme()` hook
 *
 * In watch mode it re-generates whenever a .json file in sourceDir changes,
 * debounced to avoid rapid rebuilds.
 */
export function makeThemeType(options: MakeThemeTypeOptions): void {
  const { sourceDir, outputDir, debounceMs } = options;

  if (!fs.existsSync(sourceDir)) {
    process.stderr.write(`[ink-cartridge] Error: source directory not found — "${sourceDir}"\n`);
    process.exit(1);
  }

  generate(sourceDir, outputDir, options);

  if (options.watch) {
    let timer: ReturnType<typeof setTimeout> | undefined;
    try {
      fs.watch(sourceDir, (_eventType, filename) => {
        if (!filename || !filename.endsWith('.json')) return;
        if (timer) clearTimeout(timer);
        timer = setTimeout(() => {
          process.stderr.write(`[ink-cartridge] Change detected in "${filename}", regenerating…\n`);
          generate(sourceDir, outputDir, options);
        }, debounceMs);
      });
      process.stderr.write(`[ink-cartridge] Watching "${sourceDir}" for changes (debounce: ${debounceMs}ms)…\n`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      process.stderr.write(`[ink-cartridge] Error: watch mode failed — ${msg}\n`);
      process.exit(1);
    }
  }
}

/* ------------------------------------------------------------------ */
/*  Core generate function                                            */
/* ------------------------------------------------------------------ */

function generate(sourceDir: string, outputDir: string, options: MakeThemeTypeOptions): void {
  const files = scanThemeFiles(sourceDir);

  if (files.length === 0) {
    process.stderr.write(`[ink-cartridge] Warning: no .json files found in "${sourceDir}"\n`);
    const typesContent = generateTypesContent([], []);
    const runtimeContent = generateRuntimeContent(options.packageName);
    writeOutput(outputDir, typesContent, runtimeContent);
    return;
  }

  const commonKeys = findCommonKeys(files);
  const { colorKeys, styleKeys } = classifyKeys(files, commonKeys);

  // Warn about keys not in all files
  const allKeys = new Set<string>();
  for (const f of files) for (const k of Object.keys(f.values)) allKeys.add(k);
  for (const key of allKeys) {
    if (!commonKeys.includes(key)) {
      const missingIn = files.filter((f) => !(key in f.values)).map((f) => f.id);
      process.stderr.write(
        `[ink-cartridge] Warning: key "${key}" is missing in [${missingIn.join(', ')}] — excluded from type\n`,
      );
    }
  }

  const typesContent = generateTypesContent(colorKeys, styleKeys);
  const runtimeContent = generateRuntimeContent(options.packageName);
  writeOutput(outputDir, typesContent, runtimeContent);

  process.stderr.write(
    `[ink-cartridge] Generated ${colorKeys.length} color keys + ${styleKeys.length} style keys → ${path.resolve(outputDir)}\n`,
  );
}
