// Auto-generated by ink-cartridge makeThemeType.
// Do not edit manually.

export type ThemeColorKey =
  | 'bg'
  | 'border'
  | 'danger'
  | 'muted'
  | 'primary'
  | 'success';

export type ThemeStyleKey =
  | 'borderBold'
  | 'textDim'
  | 'titleBold';

/** Union of all theme keys (color + style). */
export type ThemeKey = ThemeColorKey | ThemeStyleKey;
