// Auto-generated by ink-cartridge makeThemeType.
// Do not edit manually.

import { useTheme as rawUseTheme } from 'ink-cartridge';
import type { ThemeColorKey, ThemeStyleKey } from './theme-types.js';

/**
 * Typed theme hook. Drop-in replacement for the original `useTheme`.
 *
 * - `color()` only accepts keys classified as color values
 * - `style()` only accepts keys classified as style (boolean) values
 */
export function useTheme(): Omit<ReturnType<typeof rawUseTheme>, 'color' | 'style'> & {
  color: (key: ThemeColorKey) => string | undefined;
  style: (key: ThemeStyleKey) => boolean | undefined;
} {
  const ctx = rawUseTheme();
  return {
    ...ctx,
    color: (key: any) => ctx.color(key),
    style: (key: any) => ctx.style(key),
  };
}
